# Generated by Django 5.2.2 on 2025-06-09 10:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parent_email_teacher_email_term_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='date_commented',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 6, 9)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_employed',
            field=models.DateField(default=datetime.date(2025, 6, 9)),
        ),
        migrations.AlterField(
            model_name='term',
            name='year',
            field=models.DateField(default=datetime.date(2025, 6, 9)),
        ),
    ]
