"""
Django settings for canine project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0)w!%^$*=(5e13=5v(k9e7rh^msa+m=q7k5j5$glcjitmk*ldp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'zoo',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap4',
    'import_export',


   
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'canine.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'canine.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'ruth',
		'USER': 'root',
		'PASSWORD': 'pass',
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap4"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "AFHR",
    "copy_right": "Ruth_Kusiima",
    "site_header": 'AFHR',
    "site_logo": "images/logo.png",
    "site_logo_classes": "img-circle",
    "site_icon": "images/logo.png",
    "welcome_sign": "Welcome to the Animal feeding and health management system",
    "show_sidebar": True,
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "icon": "fas fa-home"},
        {"name": "Documentation", "url": "https://docs.djangoproject.com/en/5.1/", "new_window": True, "icon": "fas fa-book"},
        {"name": "Support", "url": "https://www.djangoproject.com/community/", "new_window": True, "icon": "fas fa-life-ring"},
    ],
    "user_menu": {
        "show_user_image": True,
        "show_username": True,
        "show_user_email": True,
        "links": [
            {"name": "Profile", "url": "/admin/auth/user/", "icon": "fas fa-user"},
            {"name": "Logout", "url": "logout/", "icon": "fas fa-sign-out-alt"},
        ],
    },
    "icons": {
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "zoo.Animal": "fas fa-paw",
        "zoo.AnimalKeeper": "fas fa-street-view",
        "zoo.Enclosure": "fas fa-home",
        "zoo.FeedingSchedule": "fas fa-utensils",
        "zoo.Supplier": "fas fa-truck",
        "zoo.Supply": "fas fa-box",
        "zoo.HealthCheck": "fas fa-stethoscope",
        "zoo.Veterinarian": "fas fa-hippo",
    },
    "footer_links": [
        {"name": "Privacy Policy", "url": "/privacy/", "new_window": False, "icon": "fas fa-shield-alt"},
        {"name": "Terms of Service", "url": "/terms/", "new_window": False, "icon": "fas fa-file-contract"},
    ],      
}
